
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -  id: trailing-whitespace
    -  id: end-of-file-fixer
    -  id: check-added-large-files
    -  id: check-ast
       files: ".*.py"
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -  id: black
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.4
    hooks:
    - id: commitizen
      stages:
      - commit-msg
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/flakeheaven/flakeheaven
    rev: 0.11.0
    hooks:
      - id: flakeheaven
