
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -  id: trailing-whitespace
    -  id: end-of-file-fixer
    -  id: check-added-large-files
    -  id: check-ast
       files: ".*.py"
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -  id: black
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
    - id: commitizen
      stages:
        - commit-msg
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/flakeheaven/flakeheaven
    rev: 2.0.0
    hooks:
      - id: flakeheaven
ci:
    autofix_commit_msg: |
        build(pre-commit): :green_heart: [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autoupdate_commit_msg: 'build(deps): :arrow_up: [pre-commit.ci] pre-commit autoupdate'
