name: Dev Workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Jobs to Run
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: Gr1N/setup-poetry@v7
      - run: poetry install
      - name: Run tests and collect coverage
        run: poetry run pytest --cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
