name: Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: |
      !startsWith(github.event.head_commit.message, 'bump:') ||
      !startsWith(github.event.head_commit.message, 'docs') ||
      !startsWith(github.event.head_commit.message, 'style') ||
      !startsWith(github.event.head_commit.message, 'chore') ||
      !startsWith(github.event.head_commit.message, 'revert') ||
      !startsWith(github.event.head_commit.message, 'ci')
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Delete Changelog
        run: rm CHANGELOG.md
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          branch: main
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
